config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :webhooks do
    post '/email_inbound', to: 'sendgrid#inbound'
    namespace 'sms' do
      post '/twilio', to: 'twilio#inbound_sms'
      post '/generic', to: 'generic#inbound_sms'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :mailbox, only: %i[show create destroy] do
        resources :emails, only: %i[index show destroy]
      end
    end
  end

  resources :phone_numbers, path: :phones, only: %i[index show], param: :number

  namespace :mailbox do
    resources :emails, only: %i[index destroy show], param: :email_id do
      member do
        get 'render_email_html'
      end
    end
    get 'inbox', action: :inbox
    get '', action: :index
    post '', action: :create, as: :create
    post 'logout', action: :logout, as: :logout
    delete '', action: :destroy, as: :destroy
    get '/:email/:token', action: :login, constraints: { email: %r{[^/]+} }, as: :login
  end

  resources :changelog, only: %i[index]

  root to: 'mailbox#index'
end

app/models/mailbox.rb
# frozen_string_literal: true

class Mailbox < ApplicationRecord
  DEFAULT_VALID_FOR = 7.days

  has_secure_token
  has_many :inbound_emails, dependent: :destroy
  validates :email, presence: true

  attribute :expires_at, :datetime, default: -> { Time.zone.now + DEFAULT_VALID_FOR }

  scope :expired, -> { where('expires_at <= ?', Time.zone.now) }

  after_destroy :log

  def self.create_custom(username, domain_id)
    domain = Domain.find domain_id
    email = "#{username}@#{domain.domain}"
    create(email: email)
  end

  def to_param
    email
  end

  private

  def log
    Log.create(action: :destroy_mailbox)
  end
end

app/controllers/api/v1/mailbox_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class MailboxController < ApiController
      before_action :validate_mailbox_token, only: %i[show destroy]
      before_action :set_mailbox, only: %i[show destroy]

      def show
        @last_email = @mailbox.inbound_emails&.first
      end

      def create
        @mailbox = MailboxService::Generator.call
        render :show, status: :created
      end

      def destroy
        @mailbox.destroy
      end

      private

      def set_mailbox
        @mailbox = Mailbox.find_by!(id: params[:id])

        head 401 unless MailboxService::TokenValidator.call(@mailbox, params[:token])
      end
    end
  end
end

app/controllers/mailbox/emails_controller.rb
# frozen_string_literal: true

# rubocop:disable Style/ClassAndModuleChildren
class Mailbox::EmailsController < ApplicationController
  include ActionView::Helpers::TextHelper

  ALLOWED_TAGS = %w[html style strong em b i p code pre tt samp kbd var sub
                    sup dfn cite big small address hr br div span h1 h2 h3 h4 h5 h6 ul ol li dl dt dd abbr
                    acronym a img blockquote del ins].freeze
  ALLOWED_ATTRIBUTES = %w[href src width id class style height alt cite datetime title class name xml:lang abbr].freeze

  before_action :validate_mailbox
  before_action :set_email, only: %i[show destroy render_email_html]

  def index
    @pagy, @emails = pagy(current_mailbox.inbound_emails, link_extra: 'data-remote="true"')
    respond_to do |format|
      format.js
    end
  end

  def show
    @email.update(read_at: Time.zone.now)
    Log.create(action: :open_email)
    respond_to do |format|
      format.js
    end
  end

  def render_email_html
    # rubocop:disable Rails/OutputSafety
    render html: sanitize(@email.html.html_safe, tags: ALLOWED_TAGS, attributes: ALLOWED_ATTRIBUTES)
    # rubocop:enable Rails/OutputSafety
  end

  def destroy
    Log.create(action: :delete_email)
    @email.destroy
  end

  private

  def set_email
    @email = InboundEmail.find_by!(id: params[:email_id], mailbox_id: current_mailbox.id)
  end
end
# rubocop:enable Style/ClassAndModuleChildren

app/controllers/mailbox_controller.rb
# frozen_string_literal: true

class MailboxController < ApplicationController
  before_action :validate_mailbox, only: %i[inbox]
  before_action :redirect_to_mailbox, only: %i[index]

  def index
    @stats = StatsProducer.call
  end

  def inbox; end

  def create
    mailbox = MailboxService::Generator.call
    create_session mailbox
    redirect_to mailbox_path
  end

  def login
    mailbox = Mailbox.find_by(email: params['email'], token: params['token'])

    create_session mailbox if mailbox
    redirect_to mailbox_path
  end

  def logout
    destroy_session
    redirect_to root_url
  end

  def destroy
    current_mailbox.destroy
    destroy_session
    redirect_to root_url
  end

  private

  def redirect_to_mailbox
    return redirect_to mailbox_inbox_path if current_mailbox
  end
end

app/helpers/mailbox_helper.rb
# frozen_string_literal: true

module MailboxHelper
end

app/views/mailbox/_login.html.erb
oi

app/views/mailbox/_modals.html.erb
<div class="modal fade" id="sessionModal" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Session URL</h5>
      </div>
      <div class="modal-body">
        <p><%= t '.session_help' %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary ml-1" data-dismiss="modal">
          <span class="d-sm-block">Close</span>
        </button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="generateModal" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Generating mailboxes</h5>
      </div>
      <div class="modal-body">
        <p><%= t '.generate_mailbox_help' %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary ml-1" data-dismiss="modal">
          <span class="d-sm-block">Close</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/mailbox/_stats.html.erb
<div class="row">
  <div class="offset-md-3 col-md-6 mt-4">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <div class="card-title-content">
          <h4 class="card-title">📈 Stats</h4>
          <% if Log.first.present? %>
            <small class="text-muted">since <%= l(Log.first.created_at, format: :long) %></small>
          <% end %>
        </div>
        <i class="bx bx-dots-vertical-rounded font-medium-3 cursor-pointer"></i>
      </div>
      <div class="card-content">
        <div class="card-body d-flex justify-content-around">
          <div class="d-inline-flex mr-xl-2" style="position: relative;">
            <div class="profit-content ml-50 mt-50">
              <h5 class="mb-0"><%= email_stats %></h5>
              <small class="text-muted">emails received</small>
            </div>
          </div>
          <div class="d-inline-flex" style="position: relative;">
            <div class="profit-content ml-50 mt-50">
              <h5 class="mb-0"><%= mailbox_stats %></h5>
              <small class="text-muted">mailboxes generated</small>
            </div>
          </div>
          <div class="d-inline-flex" style="position: relative;">
            <div class="profit-content ml-50 mt-50">
              <h5 class="mb-0"><%= sms_stats   %></h5>
              <small class="text-muted">sms received</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/mailbox/inbox.html.erb
<div class="row mb-1">
  <div class="col-12 d-flex justify-content-end">
    <span class="align-middle">
    <%= link_to '#', data: { toggle: 'modal', target: '#generateModal' } do %>
      <%= icon('fas', 'info-circle', class: 'fa-2x mr-1') %>
    <% end %>
    </span>
    <%= link_to t('.generate'), mailbox_create_path, method: :post, class: 'btn btn-success btn-sm mr-1' %>
    <%= link_to t('.logout'), mailbox_logout_path, method: :post, class: 'btn btn-primary btn-sm mr-1' %>
    <%= link_to mailbox_destroy_path, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: t('.destroy_confirmation') } do %>
      <%= icon('fas', 'trash') %>
      <%= t('.delete') %>
    <% end %>
  </div>
</div>

<div class="row mb-1">
  <div class="col-md-6 col-xs-12">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h4 class="card-title">Mailbox details</h4>
      </div>
      <div class="card-content">
        <div class="card-body">
          <p>Save these details so you don't lose any data</p>
          <fieldset class="form-group">
            <label for="email">Email</label>
            <div class="input-group">
              <input type="text" class="form-control" id="email" readonly="readonly" value="<%= current_mailbox.email %>">
              <div class="input-group-append">
                <button class="btn btn-primary copy" type="button">Copy</button>
              </div>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <%= link_to '#', data: { toggle: 'modal', target: '#sessionModal' } do %>
              <%= icon('fas', 'info-circle') %>
            <% end %>
            <label for="session">Session url</label>
            <div class="input-group">
              <input type="text" class="form-control" id="session" readonly="readonly" value="<%= mailbox_session_url current_mailbox %>">
              <div class="input-group-append">
                <button class="btn btn-primary copy" type="button">Copy</button>
              </div>
            </div>
          </fieldset>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-xs-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <form class="form form-horizontal">
              <div class="form-body">
                <div class="row">
                  <div class="col-md-5">
                    <label><%= t('.generated_at') %></label>
                  </div>
                  <div class="col-md-7 form-group">
                    <%= current_mailbox.created_at %>
                  </div>
                  <div class="col-md-5">
                    <label><%= t('.emails_received') %></label>
                  </div>
                  <div class="col-md-7 form-group">
                    <%= current_mailbox.inbound_emails.size %>
                  </div>
                  <div class="col-md-5">
                    <label><%= t('.erases_in') %></label>
                  </div>
                  <div class="col-md-7 form-group">
                    <span title="<%= current_mailbox.expires_at %>"><%= distance_of_time_in_words_to_now current_mailbox.expires_at %></span>
                  </div>
                </div>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="row mb-1">
  <div class="col-12 d-flex align-items-center justify-content-between">
    <div class="custom-control custom-switch custom-control-inline custom-switch-warning custom-switch-glow">
      <input type="checkbox" class="custom-control-input" checked="true" id="autoRefresh">
      <label class="custom-control-label mr-1" for="autoRefresh"></label>
      <span>Auto refresh</span>
    </div>
    <small class="text-muted"><%= t('.last_refresh') %>: <span id="last_refresh"></span></small>

  </div>
</div>

<div id="emails_list"></div>
<div id="email-container"></div>

<%= render partial: 'modals' %>

app/views/mailbox/index.html.erb
<div class="row">
  <div class="offset-lg-3 col-lg-6 col-xs-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <p class="card-text">
            Roasted.email is a service for disposable temporary emails. Just click generate and a random email will be created for you. No logins. No accounts. One single click.
          </p>
          <p class="card-text">
            <b>All mailboxes expire automatically after <%= distance_of_time_in_words(Mailbox::DEFAULT_VALID_FOR) %> and all the stored emails are deleted.</b> Use this service for temporary email only, otherwise you might lose your data.
          </p>
          <p class="card-text">
            If you want to access a previously used mailbox you must use the session url that was provided.
          </p>
        </div>
      </div>
    </div>
    <%= link_to t('.generate'), mailbox_create_path, method: :post, class: 'btn mb-1 btn-danger glow btn-lg btn-block' %>
  </div>
</div>

<%= render partial: 'stats', locals: { email_stats: @stats[:emails_count], mailbox_stats: @stats[:mailboxes_count], sms_stats: @stats[:sms_count] } %>

<div class="row">
  <div class="offset-lg-3 col-lg-6 col-xs-12">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <p class="card-text">
            Interested in temporary 📱 phone numbers? We offer that as well! Check them <%= link_to "here.", phone_numbers_path %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="offset-md-3 col-md-6 mt-2">
    <h4 class="card-title">Our domains</h4>
    <% Domain.all.order('RANDOM()').each do |domain| %>
      <a href="<%= domain.url %>" class="badge badge-<%= random_color %> mr-1 mb-1">@<%= domain.domain %></a>
    <% end %>
  </div>
</div>

app/views/mailbox/show.html.erb
<div class="row mb-1">
  <div class="col-6">
    <div class="card">
      <div class="card-header d-flex justify-content-between align-items-center">
        <h4 class="card-title">Mailbox details</h4>
      </div>
      <div class="card-content">
        <div class="card-body">
          <fieldset class="form-group">
            <label for="email">Email</label>
            <div class="input-group">
              <input type="text" class="form-control" id="email" readonly="readonly" value="<%= current_mailbox.email %>">
              <div class="input-group-append">
                <button class="btn btn-primary copy" type="button">Copy</button>
              </div>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <%= link_to '#', data: { toggle: 'modal', target: '#sessionModal' } do %>
              <%= icon('fas', 'info-circle') %>
            <% end %>
            <label for="session">Session url</label>
            <div class="input-group">
              <input type="text" class="form-control" id="session" readonly="readonly" value="<%= mailbox_session_url current_mailbox %>">
              <div class="input-group-append">
                <button class="btn btn-primary copy" type="button">Copy</button>
              </div>
            </div>
          </fieldset>

          <%= link_to 'Roast mailbox', mailbox_destroy_path, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: t('mailbox_destroy_confirmation') } %>

        </div>
      </div>
    </div>
  </div>
  <div class="col-6">
    <div class="card">
      <div class="card-content">
        <div class="card-body">
          <form class="form form-horizontal">
              <div class="form-body">
                <div class="row">
                  <div class="col-md-5">
                    <label>Mailbox generated at</label>
                  </div>
                  <div class="col-md-7 form-group">
                    <%= current_mailbox.created_at %>
                  </div>
                  <div class="col-md-5">
                    <label>Emails received</label>
                  </div>
                  <div class="col-md-7 form-group">
                    <%= current_mailbox.inbound_emails.size %>
                  </div>
                  <div class="col-md-5">
                    <label>Erases itself in</label>
                  </div>
                  <div class="col-md-7 form-group">
                    <span title="<%= current_mailbox.expires_at %>"><%= distance_of_time_in_words_to_now current_mailbox.expires_at %></span>
                  </div>
                </div>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="row mb-1">
  <div class="col-12">
    <button id="refresh" class="btn btn-primary glow">Refresh</button>
    <small class="text-muted float-right">Last refresh: <span id="last_refresh"></span></small>

  </div>
</div>

<div id="emails_list"></div>

<%= render partial: 'session_modal' %>


<script>
  const refreshButton = $('#refresh');
  const lastRefresh = $('#last_refresh');

  function loadEmails() {
    refreshButton.prop('disabled', true).text('Refreshing...');
    $.ajax({
      "type": "GET",
      "url": "/mailbox/emails",
      "dataType": "script",
    }).done(() => {
      refreshButton.prop('disabled', false).text('Refresh');
      lastRefresh.text(new Date().toLocaleString())
    });
  }

  window.addEventListener("turbolinks:load", loadEmails);

  refreshButton.click(loadEmails);


</script>