config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :webhooks do
    post '/email_inbound', to: 'sendgrid#inbound'
    namespace 'sms' do
      post '/twilio', to: 'twilio#inbound_sms'
      post '/generic', to: 'generic#inbound_sms'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :mailbox, only: %i[show create destroy] do
        resources :emails, only: %i[index show destroy]
      end
    end
  end

  resources :phone_numbers, path: :phones, only: %i[index show], param: :number

  namespace :mailbox do
    resources :emails, only: %i[index destroy show], param: :email_id do
      member do
        get 'render_email_html'
      end
    end
    get 'inbox', action: :inbox
    get '', action: :index
    post '', action: :create, as: :create
    post 'logout', action: :logout, as: :logout
    delete '', action: :destroy, as: :destroy
    get '/:email/:token', action: :login, constraints: { email: %r{[^/]+} }, as: :login
  end

  resources :changelog, only: %i[index]

  root to: 'mailbox#index'
end

app/models/phone_number.rb
# frozen_string_literal: true

class PhoneNumber < ApplicationRecord
  has_many :inbound_sms, class_name: 'InboundSms', dependent: :destroy
  validates :number, :country_iso3166, presence: true

  attribute :available, :boolean, default: -> { true }
  scope :active, -> { where(available: true) }

  def country_name
    ISO3166::Country.new(country_iso3166).name
  end

  def display_name
    number
  end

  def to_param
    number[1..-1]
  end
end

app/controllers/phone_numbers_controller.rb
# frozen_string_literal: true

class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: %i[show]

  def index
    @phones = PhoneNumber.active
    country = params[:country_code]
    @phones = @phones.where(country_iso3166: country) if country
  end

  def show
    @pagy, @sms = pagy @phone.inbound_sms.order(received_at: :desc)
  end

  private

  def set_phone_number
    @phone = PhoneNumber.find_by!(number: "+#{params[:number]}")
  end
end

app/views/phone_numbers/_phone_card.html.erb
<div class="card text-white bg-danger bg-lighten-1 text-center">
  <div class="card-content">
    <div class="card-body">
      <%= image_tag flag_url(phone), class: 'phone-flag mb-1 img-fluid', alt: phone.country_name %>
      <h3 class="card-title text-white"><%= phone.country_name %></h3>
      <p class="card-text"><%= phone.number %></p>
      <% unless defined?(no_link) %>
        <%= link_to "Use", phone_number_path(phone), class: 'btn btn-sm btn-outline-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/phone_numbers/_sms_entry.html.erb
<tr class="sms_entry" data-sms-id="<%= sms_entry.id %>">
  <td>
    <div class="ml-1">
      <h6 class="text-bold-500 mb-0"><%= sms_entry.from_name %></h6>
      <small class="text-muted"><%= sms_entry.from %></small>
    </div>
  </td>
  <td>
    <p class="mb-0"><%= sms_entry.body %></p>
  </td>
  <td>
    <small class="text-muted" title="<%= sms_entry.received_at %>"><%= distance_of_time_in_words_to_now sms_entry.received_at %> ago</span>
  </td>
</tr>

app/views/phone_numbers/index.html.erb
<h1><%= t '.title' %></h1>
<p class="mb-4"><%= t '.description' %></p>

<div class="container mb-4">
  <div class="row">
    <div class="offset-lg-3 col-lg-6 col-xs-12">
      <% @phones.to_a.each_slice(2) do |pair| %>
        <div class="row">
          <div class="col">
            <%= render partial: 'phone_card', locals: { phone: pair.first } %>
          </div>
          <% if pair.second %>
            <div class="col">
              <%= render partial: 'phone_card', locals: { phone: pair.second } %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/phone_numbers/show.html.erb
<div class="content-header row">
  <div class="content-header-left col-12 mb-2 mt-1">
    <div class="row breadcrumbs-top">
      <div class="col-12">
        <%= link_to "Back", phone_numbers_path %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3">
    <%= render partial: 'phone_card', locals: { phone: @phone, no_link: true } %>
  </div>
  <div class="col-9">
    <ul>
      <li>Page does not automatically refresh.</li>
      <li>Messages are removed after <%= distance_of_time_in_words(InboundSms::EXPIRES_AFTER) %></li>
      <li>Be aware that anyone can see your messages for this number</li>
      <li>Please do not verify important information</li>
    </ul>
  </div>
</div>

<div class="row mb-1">
  <div class="col-12 d-flex align-items-center justify-content-between">
    <button onclick="reloadWithTurbolinks()" class="btn btn-primary">Refresh</button>
    <small class="text-muted"><%= t('mailbox.inbox.last_refresh') %>: <span><%= Time.now %></span></small>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-content">
        <div class="table-responsive">
          <table class="table table-striped mb-0">
            <colgroup>
              <col span="1">
              <col span="2">
              <col span="1">
            </colgroup>
            <thead>
              <tr>
                <th><%= t('.from') %></th>
                <th><%= t('.message') %></th>
                <th><%= t('.time') %></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: 'sms_entry', collection: @sms %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>