config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :webhooks do
    post '/email_inbound', to: 'sendgrid#inbound'
    namespace 'sms' do
      post '/twilio', to: 'twilio#inbound_sms'
      post '/generic', to: 'generic#inbound_sms'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :mailbox, only: %i[show create destroy] do
        resources :emails, only: %i[index show destroy]
      end
    end
  end

  resources :phone_numbers, path: :phones, only: %i[index show], param: :number

  namespace :mailbox do
    resources :emails, only: %i[index destroy show], param: :email_id do
      member do
        get 'render_email_html'
      end
    end
    get 'inbox', action: :inbox
    get '', action: :index
    post '', action: :create, as: :create
    post 'logout', action: :logout, as: :logout
    delete '', action: :destroy, as: :destroy
    get '/:email/:token', action: :login, constraints: { email: %r{[^/]+} }, as: :login
  end

  resources :changelog, only: %i[index]

  root to: 'mailbox#index'
end

app/views/layouts/_fathom_track.html.erb
<% if Rails.env.production? && ENV['FATHOM_ID'] %>
  <script>
    (function(f, a, t, h, o, m){
      a[h]=a[h]||function(){
        (a[h].q=a[h].q||[]).push(arguments)
      };
      o=f.createElement('script'),
      m=f.getElementsByTagName('script')[0];
      o.async=1; o.src=t; o.id='fathom-script';
      m.parentNode.insertBefore(o,m)
    })(document, window, '<%= ENV.fetch("FATHOM_TRACKER_URL") { "//cdn.usefathom.com/tracker.js" } %>', 'fathom');
    fathom('set', 'siteId', '<%= ENV['FATHOM_ID'] %>');
    fathom('trackPageview');
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer footer-static footer-dark">
  <div class="container">
    <div class="row mb-2">
      <div class="col-12">
        <p class="clearfix mb-0">
          <div class="float-left">
            <h6 class="mb-0"><%= t('app_name') %> <%= link_to "(#{::VERSION})", github_commit_url(::COMMIT) %></h6>
            <ul class="links">
              <li><%= link_to 'Phone Numbers', phone_numbers_path %></li>
              <li><%= link_to 'API', rswag_ui_path %></li>
              <li><%= link_to 'Changelog', changelog_index_path %></li>
              <li><%= link_to 'Privacy', '#', data: { toggle: 'modal', target: '#privacyModal' } %></li>
              <li></li>
            </ul>
          </div>
          <span class="float-right d-sm-inline-block d-none">Developed by<a class="text-uppercase" href="https://github.com/andrepcg" target="_blank">andré perdigão</a></span>
        </p>
      </div>
    </div>
  </div>
</footer>

<div class="modal fade" id="privacyModal" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Privacy</h5>
      </div>
      <div class="modal-body">
        <p>All emails and sms received in Roasted.email are not processed in any way. No personal information is collected whatsoever.</p>
        <p>Mailboxes and their corresponding emails are destroyed after <%= distance_of_time_in_words(Mailbox::DEFAULT_VALID_FOR) %>.</p>
        <p>SMS are destroyed after 2 hours of being received.</p>
        <p>Only general system statistics are collected to provide the stats panel. These stats are totally data-free, meaning it's merely a counter to track how many of each the system has received, their not tied to a specific mailbox or phone number.</p>
        <p>Check the code on <a href="https://github.com/andrepcg/roasted-mail">Github</a>.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary ml-1" data-dismiss="modal">
          <span class="d-sm-block">Close</span>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV['META_TITLE'] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description" content="<%= ENV['META_DESCRIPTION'] %>">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500,600%7CIBM+Plex+Sans:300,400,500,600,700" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'mailbox', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'phones', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/fathom_track' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'inbox' %>
    <%= javascript_pack_tag 'phones' %>
    <%= render 'application/favicon' %>

    <meta name="controller_name" content="<%= controller_name %>">
    <meta name="action_name" content="<%= action_name %>">

        <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= ENV['META_TITLE'] %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= ENV['META_IMAGE'] %>" />
    <meta property="og:description" content="<%= ENV['META_DESCRIPTION'] %>" />
    <meta property="og:site_name" content="<%= ENV['META_TITLE'] %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<%= ENV['META_TITLE'] %>">
    <meta name="twitter:description" content="<%= ENV['META_DESCRIPTION'] %>">
    <meta name="twitter:image:src" content="<%= ENV['META_IMAGE'] %>">
  </head>

  <body class="dark-layout">
    <main id="content" role="main">
      <div class="container">
        <div class="row mb-2">
          <div class="col text-center mt-2">
            <%= link_to mailbox_path, data: { turbolinks: false } do %>
              <%= image_tag("roasted.svg", alt: t('app_name'), title: t('app_name'), class: 'fit')%>
            <% end %>
          </div>
        </div>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>